AWSTemplateFormatVersion: 2010-09-09

Description: The IAM Resources for app project

Resources:
  AppIamPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - ec2:DescribeVolumes
              - ec2:DescribeTags
            Resource: "*"
      ManagedPolicyName: ServicePolicy
