AWSTemplateFormatVersion: 2010-09-09

Description: The IAM Resources for pet project

Resources:
  PetIamPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - appmesh:StreamAggregatedResources
            Resource:
              - arn:aws:appmesh:ap-southeast-2:291148202449:mesh/test-mesh/virtualNode/pet-service_test
              - arn:aws:appmesh:ap-southeast-2:291148202449:mesh/prod-mesh/virtualNode/pet-service_prod
          - Effect: Allow
            Action:
              - xray:PutTraceSegments
              - xray:PutTelemetryRecords
              - xray:GetSamplingRules
              - xray:GetSamplingTargets
              - xray:GetSamplingStatisticSummaries
            Resource: "*"
          - Effect: Allow
            Action:
              - cloudwatch:PutMetricData
              - ec2:DescribeVolumes
              - ec2:DescribeTags
              - logs:PutLogEvents
              - logs:DescribeLogStreams
              - logs:DescribeLogGroups
              - logs:CreateLogStream
              - logs:CreateLogGroup
            Resource: "*"
          - Effect: Allow
            Action:
              - ssm:GetParameter
            Resource: "arn:aws:ssm:*:*:parameter/AmazonCloudWatch-*"
      ManagedPolicyName: PetPolicy
